//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BemBankApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hesaplar
    {
        public int ID { get; set; }
        public Nullable<int> Musteri_ID { get; set; }
        public string KartNo { get; set; }
        public string CVV { get; set; }
        public string SonKullanmaAy { get; set; }
        public string SonKullanmaYil { get; set; }
        public Nullable<decimal> Bakiye { get; set; }
        public Nullable<bool> Aktif { get; set; }
    }
}
